print('Sage\'s Wedding Cake Price Calculator')
people = int(input('Total People Attending: '))
cakeABase = (15 * 15) + 12.5
cakeBBase = (15 * 14) + (12.5 * 2)
cakeCBase = (15 * 16) + (12.5 * 1.5)

print('----------------------------------------')
print('Cake A')
print('Labor Cost:     \t$' + str(round(cakeABase * (people / 30), 2)))
print('Cost to Make:   \t$' + str(round((cakeABase + 35) * (people / 30), 2)))
print('Charge Customer: \t$' + str(round((cakeABase + 35) * (people / 30) + ((cakeABase + 35) * (people / 30) * .1), 2)))
print('----------------------------------------')
print('Cake B')
print('Labor Cost:     \t$' + str(round(cakeBBase * (people / 30), 2)))
print('Cost to Make:   \t$' + str(round((cakeBBase + 30) * (people / 30), 2)))
print('Charge Customer: \t$' + str(round((cakeBBase + 30) * (people / 30) + ((cakeBBase + 30) * (people / 30) * .1), 2)))
print('----------------------------------------')
print('Cake C')
print('Labor Cost:     \t$' + str(round(cakeCBase * (people / 30), 2)))
print('Cost to Make:   \t$' + str(round((cakeCBase + 40) * (people / 30), 2)))
print('Charge Customer: \t$' + str(round((cakeCBase + 40) * (people / 30) + ((cakeCBase + 40) * (people / 30) * .1), 2)))
